#!/bin/sh

. /lib/functions.sh

threads=$(cat /proc/cpuinfo | grep "processor" | wc -l)
running=0

server_ping(){
        let "running+=1"

        {
                server="$(uci get shadowsocksr.$1.server)"
                name="$(uci get shadowsocksr.$1.name)"
                time=$(fping -c 1 -t 500ms ${server} 2> /dev/null | grep -o '[0-9]*.[0-9]* ms' | awk '{print $1}')

                [ -z "$time" ] && time='NaN'
               uci set shadowsocksr.$1.ping="${time}"

                echo "${name} : ${time} ms"
        } &

        [ "$running" -ge "$threads" ] && wait && let "running-=1"
}

config_load shadowsocksr
config_foreach server_ping server
uci commit shadowsocksr