#!/bin/sh
. /lib/functions.sh

decode() {
	# accept pipe data
	rep=$(tr - + | tr _ /)
	case "$((${#rep} % 4))" in
		2) rep="$rep==" ;;
		3) rep="$rep=" ;;
		*) ;;
	esac
	echo "$rep" | base64 -d 2> /dev/null
}

decode_protocol_link() {
	link="$1"
	info="$(echo "${link#*://}" | decode)"
	case "${link%%:*}" in
	ssr)
		IFS=:\  read -r server server_port protocol method obfs password <<- EOF
			${info%%/?*}
		EOF

		while IFS='=' read -r key value; do
			[ -n "$value" ] && eval "$key=$(echo "$value" | decode)"
		done <<- EOF
			$(echo "${info#*/?}" | tr '&' '\n')
		EOF

		time="$(ping -c 1 -W 1 ${server} 2>&1 | grep -o 'time=[0-9]*.[0-9]' | awk -F '=' '{print$2}')"

		cfg=$(uci add shadowsocksr server)
		uci batch <<-EOF
		set shadowsocksr.$cfg.server="$server"
		set shadowsocksr.$cfg.server_port="$server_port"
		set shadowsocksr.$cfg.password="$(echo "$password" | decode)"
		set shadowsocksr.$cfg.encryption="$method"
		set shadowsocksr.$cfg.protocol="$protocol"
		set shadowsocksr.$cfg.protocol_param="${protoparam:-}"
		set shadowsocksr.$cfg.obfs="$obfs"
		set shadowsocksr.$cfg.obfs_param="${obfsparam:-}"
		set shadowsocksr.$cfg.group="${group:-NoGroup}"
		set shadowsocksr.$cfg.name="${remarks:-Null}"
		set shadowsocksr.$cfg.ping="${time:-NaN}"
		EOF
		echo "add ${group:-NoGroup} ${remarks:-Null}"
		;;
	http|https)
		echo "decode https"
		for l in $(curl -Ss "$link" | decode); do
			decode_protocol_link "$l"
		done
		;;
	*)
		# support downloaded content of subscription link
		for possible_link in $info; do
			decode_protocol_link "$possible_link"
		done
		;;
	esac
}

ssr_server_remove(){
	if [ "$(uci get shadowsocksr.$1.group)" = "$2" ];then
		uci delete shadowsocksr.$1
	fi
}

ssr_subscribe(){
	group="$(uci get shadowsocksr.$1.group)"
	config_foreach ssr_server_remove "server" "$group"
	decode_protocol_link "$(uci get shadowsocksr.$1.url)"
}

config_load shadowsocksr
config_foreach ssr_subscribe "subscribe"
uci commit shadowsocksr