#!/bin/sh -e
#
# Copyright (C) 2017 Yousong Zhou <yszhou4tech@gmail.com>
#
# The design idea was derived from ss-rules by Jian Chang <aa65535@live.com>
# Modyfied by William
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

__errmsg() {
	echo "ssr-rules: $*" >&2
}

if [ "$1" = "-6" ]; then
	if ! ip6tables -t nat -L -n &>/dev/null; then
		__errmsg "Skipping ipv6.  Requires ip6tables-mod-nat"
		exit 1
	fi
	o_use_ipv6=1; shift
fi

ssr_rules_usage() {
	cat >&2 <<EOF
Usage: ssr-rules [options]

	-6              Operate on address family IPv6
	                When present, must be the first argument
	-h, --help      Show this help message then exit
	-f, --flush     Flush rules, ipset then exit
	-l <port>       Local port number of ssr-redir with TCP mode
	-L <port>       Local port number of ssr-redir with UDP mode
	-s <ips>        List of ip addresses of remote shadowsocksr server
	--ifnames       Only apply rules on packets from these ifnames
	--src-bypass <ips|cidr>
	--src-forward <ips|cidr>
	--src-checkdst <ips|cidr>
	--src-default <bypass|forward|checkdst>
	                Packets will have their src ip checked in order against
	                bypass, forward, checkdst list and will bypass, forward
	                through, or continue to have their dst ip checked
	                respectively on the first match.  Otherwise, --src-default
	                decide the default action
	--dst-bypass <ips|cidr>
	--dst-forward <ips|cidr>
	--dst-bypass-file <file>
	--dst-forward-file <file>
	--dst-default <bypass|forward>
	                Same as with their --src-xx equivalent
	--dst-forward-recentrst
	                Forward those packets whose destinations have recently
	                sent to us multiple tcp-rst packets
	--local-default <bypass|forward|checkdst>
	                Default action for local out TCP traffic

The following ipsets will be created by ssr-rules.  They are also intended to be
populated by other programs like dnsmasq with ipset support

	ssr_rules_src_bypass
	ssr_rules_src_forward
	ssr_rules_src_checkdst
	ssr_rules_dst_bypass
	ssr_rules_dst_forward
EOF
}

o_dst_bypass4_="
	0.0.0.0/8
	10.0.0.0/8
	100.64.0.0/10
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.0.0.0/24
	192.0.2.0/24
	192.31.196.0/24
	192.52.193.0/24
	192.88.99.0/24
	192.168.0.0/16
	192.175.48.0/24
	198.18.0.0/15
	198.51.100.0/24
	203.0.113.0/24
	224.0.0.0/4
	240.0.0.0/4
	255.255.255.255
"
o_dst_bypass6_="
	::1/128
	::/128
	::ffff:0:0/96
	64:ff9b:1::/48
	100::/64
	2001:2::/48
	2001:db8::/32
	fe80::/10
	2001::/23
	fc00::/7
"
o_src_default=bypass
o_dst_default=bypass
o_local_default=bypass

alias grep_af="sed -ne '/:/!p'"
o_dst_bypass_="$o_dst_bypass4_"
if [ -n "$o_use_ipv6" ]; then
	alias grep_af="sed -ne /:/p"
	alias iptables=ip6tables
	alias iptables-save=ip6tables-save
	alias iptables-restore=ip6tables-restore
	alias ip="ip -6"
	o_af=6
	o_dst_bypass_="$o_dst_bypass6_"
fi

ssr_rules_parse_args() {
	while [ "$#" -gt 0 ]; do
		case "$1" in
			-h|--help) ssr_rules_usage; exit 0;;
			-f|--flush) ssr_rules_flush; exit 0;;
			-l) o_redir_tcp_port="$2"; shift 2;;
			-L) o_redir_udp_port="$2"; shift 2;;
			-s) o_remote_servers="$2"; shift 2;;
			--ifnames) o_ifnames="$2"; shift 2;;
			--ipt-extra) o_ipt_extra="$2"; shift 2;;
			--src-default) o_src_default="$2"; shift 2;;
			--dst-default) o_dst_default="$2"; shift 2;;
			--local-default) o_local_default="$2"; shift 2;;
			--src-bypass) o_src_bypass="$2"; shift 2;;
			--src-forward) o_src_forward="$2"; shift 2;;
			--src-checkdst) o_src_checkdst="$2"; shift 2;;
			--dst-bypass) o_dst_bypass="$2"; shift 2;;
			--dst-forward) o_dst_forward="$2"; shift 2;;
			--dst-forward-recentrst) o_dst_forward_recentrst=1; shift 1;;
			--dst-bypass-file) o_dst_bypass_file="$2"; shift 2;;
			--dst-forward-file) o_dst_forward_file="$2"; shift 2;;
			--dst-net-forward-file) o_dst_net_forward_file="$2"; shift 2;;
			--dst-net-dns-server) o_dst_net_dns_server="$2"; shift 2;;
			--dst-net-dns-port) o_dst_net_dns_port="$2"; shift 2;;
			*) __errmsg "unknown option $1"; return 1;;
		esac
	done

	if [ -z "$o_redir_tcp_port" -a -z "$o_redir_udp_port" ]; then
		__errmsg "Requires at least -l or -L option"
		return 1
	fi
	if [ -n "$o_dst_forward_recentrst" ] && ! iptables -m recent -h >/dev/null; then
		__errmsg "Please install iptables-mod-conntrack-extra"
		return 1
	fi
	o_remote_servers="$(for s in $o_remote_servers; do resolveip "$s" | grep_af; done)"
}

ssr_rules_flush() {
	local setname

	iptables-save --counters | grep -v ssr_rules_ | iptables-restore --counters
	while ip rule del fwmark 1 lookup 100 2>/dev/null; do true; done
	ip route flush table 100 2>/dev/null || true
	for setname in $(ipset -n list | grep "ssr_rules${o_af}_"); do
		ipset destroy "$setname" 2>/dev/null || true
	done

	sed -i "/dnsmasq.ssr/d" /etc/dnsmasq.conf >/dev/null 2>&1
	[ -d "/tmp/dnsmasq.ssr" ] && rm -rf /tmp/dnsmasq.ssr
	/etc/init.d/dnsmasq restart >/dev/null 2>&1
}

ssr_rules_ipset_init() {
	ipset --exist restore <<-EOF
		create ssr_rules${o_af}_src_bypass hash:net family inet$o_af hashsize 64
		create ssr_rules${o_af}_src_forward hash:net family inet$o_af hashsize 64
		create ssr_rules${o_af}_src_checkdst hash:net family inet$o_af hashsize 64
		create ssr_rules${o_af}_dst_bypass hash:net family inet$o_af hashsize 64
		create ssr_rules${o_af}_dst_bypass_ hash:net family inet$o_af hashsize 64
		create ssr_rules${o_af}_dst_forward hash:net family inet$o_af hashsize 64
		create ssr_rules${o_af}_dst_forward_rrst_ hash:ip family inet$o_af hashsize 8 timeout 3600
		$(ssr_rules_ipset_mkadd ssr_rules${o_af}_dst_bypass_ "$o_dst_bypass_ $o_remote_servers")
		$(ssr_rules_ipset_mkadd ssr_rules${o_af}_src_bypass "$o_src_bypass")
		$(ssr_rules_ipset_mkadd ssr_rules${o_af}_src_forward "$o_src_forward")
		$(ssr_rules_ipset_mkadd ssr_rules${o_af}_src_checkdst "$o_src_checkdst")
		$(ssr_rules_ipset_mkadd ssr_rules${o_af}_dst_bypass "$o_dst_bypass $(cat "$o_dst_bypass_file" 2>/dev/null | sed '/^#/d')")
		$(ssr_rules_ipset_mkadd ssr_rules${o_af}_dst_forward "$o_dst_forward $(cat "$o_dst_forward_file" 2>/dev/null | sed '/^#/d')")
	EOF
}

ssr_rules_ipset_mkadd() {
	local setname="$1"; shift
	local i

	for i in $*; do
		echo "add $setname $i"
	done | grep_af
}

ssr_rules_iptchains_init() {
	ssr_rules_iptchains_init_tcp
	ssr_rules_iptchains_init_udp
}

ssr_rules_iptchains_init_tcp() {
	local local_target

	[ -n "$o_redir_tcp_port" ] || return 0

	ssr_rules_iptchains_init_ nat tcp

	case "$o_local_default" in
		checkdst) local_target=ssr_rules_dst ;;
		forward) local_target=ssr_rules_forward ;;
		bypass|*) return 0;;
	esac

	iptables-restore --noflush <<-EOF
		*nat
		:ssr_rules_local_out -
		-I OUTPUT 1 -p tcp -j ssr_rules_local_out
		-A ssr_rules_local_out -m set --match-set ssr_rules${o_af}_dst_bypass_ dst -j RETURN
		-A ssr_rules_local_out $o_ipt_extra -j $local_target
		COMMIT
	EOF
}

ssr_rules_iptchains_init_udp() {
	[ -n "$o_redir_udp_port" ] || return 0
	ssr_rules_iptchains_init_ mangle udp
}

ssr_rules_iptchains_init_() {
	local table="$1"
	local proto="$2"
	local forward_rules
	local src_default_target dst_default_target
	local recentrst_mangle_rules recentrst_addset_rules

	case "$proto" in
		tcp)
			forward_rules="-A ssr_rules_forward -p tcp -j REDIRECT --to-ports $o_redir_tcp_port"
			if [ -n "$o_dst_forward_recentrst" ]; then
				recentrst_mangle_rules="
					*mangle
					-I PREROUTING 1 -p tcp -m tcp --tcp-flags RST RST -m recent --name ssr_rules_recentrst --set --rsource
					COMMIT
				"
				recentrst_addset_rules="
					-A ssr_rules_dst -m recent --name ssr_rules_recentrst --rcheck --rdest --seconds 3 --hitcount 3 -j SET --add-set ssr_rules${o_af}_dst_forward_rrst_ dst --exist
					-A ssr_rules_dst -m set --match-set ssr_rules${o_af}_dst_forward_rrst_ dst -j ssr_rules_forward
				"
			fi
			;;
		udp)
			ip rule add fwmark 1 lookup 100
			ip route add local default dev lo table 100
			forward_rules="-A ssr_rules_forward -p udp -j TPROXY --on-port "$o_redir_udp_port" --tproxy-mark 0x01/0x01"
			;;
	esac
	case "$o_src_default" in
		forward) src_default_target=ssr_rules_forward ;;
		checkdst) src_default_target=ssr_rules_dst ;;
		bypass|*) src_default_target=RETURN ;;
	esac
	case "$o_dst_default" in
		forward) dst_default_target=ssr_rules_forward ;;
		bypass|*) dst_default_target=RETURN ;;
	esac
	sed -e '/^\s*$/d' -e 's/^\s\+//' <<-EOF | iptables-restore --noflush
		*$table
		:ssr_rules_pre_src -
		:ssr_rules_src -
		:ssr_rules_dst -
		:ssr_rules_forward -
		$(ssr_rules_iptchains_mkprerules "$proto")
		-A ssr_rules_pre_src -m set --match-set ssr_rules${o_af}_dst_bypass_ dst -j RETURN
		-A ssr_rules_pre_src $o_ipt_extra -j ssr_rules_src
		-A ssr_rules_src -m set --match-set ssr_rules${o_af}_src_bypass src -j RETURN
		-A ssr_rules_src -m set --match-set ssr_rules${o_af}_src_forward src -j ssr_rules_forward
		-A ssr_rules_src -m set --match-set ssr_rules${o_af}_src_checkdst src -j ssr_rules_dst
		-A ssr_rules_src -j $src_default_target
		-A ssr_rules_dst -m set --match-set ssr_rules${o_af}_dst_bypass dst -j RETURN
		-A ssr_rules_dst -m set --match-set ssr_rules${o_af}_dst_forward dst -j ssr_rules_forward
		$recentrst_addset_rules
		-A ssr_rules_dst -j $dst_default_target
		$forward_rules
		COMMIT
		$recentrst_mangle_rules
	EOF
}

ssr_rules_iptchains_mkprerules() {
	local proto="$1"

	if [ -z "$o_ifnames" ]; then
		echo "-I PREROUTING 1 -p $proto -j ssr_rules_pre_src"
	else
		echo $o_ifnames \
			| tr ' ' '\n' \
			| sed "s/.*/-I PREROUTING 1 -i \\0 -p $proto -j ssr_rules_pre_src/"
	fi
}

ssr_rules_dnsmasq_init() {
	mkdir -p /tmp/dnsmasq.ssr

	cat $o_dst_net_forward_file | sed -r 's#(.+)#server=/\1/'$o_dst_net_dns_server'\#'$o_dst_net_dns_port'#g' > /tmp/dnsmasq.ssr/dst_net.forward
	cat $o_dst_net_forward_file | sed -r 's#(.+)#ipset=/\1/'ssr_rules_dst_forward'#g' >> /tmp/dnsmasq.ssr/dst_net.forward

	echo 'conf-dir=/tmp/dnsmasq.ssr' >> /etc/dnsmasq.conf
	/etc/init.d/dnsmasq restart >/dev/null 2>&1
}

ssr_rules_parse_args "$@"
ssr_rules_flush
ssr_rules_ipset_init
ssr_rules_iptchains_init
ssr_rules_dnsmasq_init
