#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

sed -i '/Kernel Version/i\\t\t<div class="tr"><div class="td left" width="33%"><%:WIFI Temperature%></div><div class="td left">' \
/usr/lib/lua/luci/view/admin_status/index/10-system.htm
sed -i '/Kernel Version/i\\t\t\t2G:<%=luci.sys.exec("cut -c1-2 /sys/class/hwmon/hwmon0/temp1_input")%>℃  ,' \
/usr/lib/lua/luci/view/admin_status/index/10-system.htm
sed -i '/Kernel Version/i\\t\t\t5G:<%=luci.sys.exec("cut -c1-2 /sys/class/hwmon/hwmon1/temp1_input")%>℃   ' \
/usr/lib/lua/luci/view/admin_status/index/10-system.htm
sed -i '/Kernel Version/i\\t\t</div></div>' \
/usr/lib/lua/luci/view/admin_status/index/10-system.htm

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0



