#
# Copyright (C) 2020-2020 William <gw826943555@qq.com>
#
# This is free software, licensed under the MIT License.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI syslog managment module
LUCI_DEPENDS:=+luci-base +syslog-fc

PKG_MAINTAINER:=William <gw826943555@qq.com>
PKG_LICENSE:=MIT

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature