#!/bin/sh

FORMAT=${1:-plain}

if [ ! -x /sbin/logread ]; then
	echo "/sbin/logread not exists"
	exit 1
fi

if [ ! -x /usr/bin/syslog_fc ]; then
	echo "/usr/bin/syslog_fc not exists"
	exit 1
fi

case "$FORMAT" in
	json|csv)
		/sbin/logread | /usr/bin/syslog_fc -f ${FORMAT} -s
		;;

	*)
		/sbin/logread
		;;
esac
