#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@passwall[-1]
	add ucitrack passwall
	set ucitrack.@passwall[-1].init=passwall
	commit ucitrack
EOF

echo "" > /etc/dnsmasq.conf
killall -q -9 shadowsocks-libev shadowsocksr-libev
rm -f /tmp/luci-indexcache
exit 0
